### ISSUE TITLE
Refactoring the module name - Broke half the tests ... but the pry looks good?

### ISSUE THREAD

**Issue by Mirv** [iCodeSometime/asynchronize#15]
I've been over this one a few times & I'm not understanding why any errors, as it looks like the path, name module creation is working... I didn't touch the original two private methods or the `.instance_evaluation`

First, my tests, then the pry, then the code ...
```
    18: def self.asynchronize(*methods)
    19:   async_container = Asynchronize.get_container_for(self)
 => 20:   require 'pry'; binding.pry
    21: 
    22:   async_container.instance_eval do
    23:     Asynchronize._define_methods_on_object(methods, self)
    24:   end
    25: end

[1] pry(BasicSpec::Test)> async_container
=> Asynchronize::TestAsynchronized
[2] pry(BasicSpec::Test)> async_container.class
=> Module

[7] pry(BasicSpec::Test)> async_container.instance_eval do        
[7] pry(BasicSpec::Test)*   Asynchronize._define_methods_on_object(methods, self)          
[7] pry(BasicSpec::Test)* end          
=> [:othertest]
```
Here are my minitest spec results ...
```
mirv:~/workspace (ver2_rev008) $ /home/ubuntu/workspace/lib/asynchronize.rb:86: warning: method redefined; discarding old get_container_for
/home/ubuntu/workspace/lib/asynchronize.rb:28: warning: previous definition of get_container_for was here
Run options: --seed 51718

# Running:

F/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old othertest
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of othertest was here
E/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old othertest
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of othertest was here
EF/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of test was here
F./home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old notamethod
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of notamethod was here
../home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of test was here
F/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of test was here
E/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of test was here
E/home/ubuntu/workspace/lib/asynchronize.rb:62: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:72: warning: previous definition of test was here
EE

Finished in 0.004878s, 2665.1549 runs/s, 1435.0834 assertions/s.

  1) Failure:
Asynchronize::when we call asynchronized before defining the method#test_0001_should return a thread [/home/ubuntu/workspace/spec/spec.rb:79]:
The asynchronized method without a block did not return a thread..
Expected: Thread
  Actual: Fixnum

  2) Error:
Asynchronize::when we call asynchronized before defining the method#test_0002_should provide the result in return_value:
NoMethodError: undefined method `join' for 5:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:83:in `block (3 levels) in <class:BasicSpec>'

  3) Error:
Asynchronize::when we call asynchronized before defining the method#test_0003_should provide the result as a block parameter:
NoMethodError: undefined method `join' for 5:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:89:in `block (3 levels) in <class:BasicSpec>'

  4) Failure:
Asynchronize::when we asynchronize a method#test_0004_should not affect methods on other classes when called before [/home/ubuntu/workspace/spec/spec.rb:35]:
Expected: Thread
  Actual: Fixnum

  5) Failure:
Asynchronize::when we asynchronize a method#test_0005_should not affect methods on other classes when called after [/home/ubuntu/workspace/spec/spec.rb:44]:
Expected: Thread
  Actual: Fixnum

  6) Failure:
Asynchronize::when we call asynchronized after defining the method#test_0001_should return a thread [/home/ubuntu/workspace/spec/spec.rb:54]:
The asynchronized method without a block did not return a thread..
Expected: Thread
  Actual: Fixnum

  7) Error:
Asynchronize::when we call asynchronized after defining the method#test_0002_should provide the result in return_value:
NoMethodError: undefined method `join' for 5:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:58:in `block (3 levels) in <class:BasicSpec>'

  8) Error:
Asynchronize::when we call asynchronized after defining the method#test_0003_should provide the result as a block parameter:
NoMethodError: undefined method `join' for 5:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:64:in `block (3 levels) in <class:BasicSpec>'

  9) Error:
Asynchronize::when inheriting from another class#test_0002_should be able to call super when super has been asynchronized:
NoMethodError: undefined method `join' for 5:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:119:in `test'
    /home/ubuntu/workspace/spec/spec.rb:122:in `block (3 levels) in <class:BasicSpec>'

 10) Error:
Asynchronize::when inheriting from another class#test_0001_should be able to call super when it's been asynchronized:
NoMethodError: undefined method `join' for 6:Fixnum
    /home/ubuntu/workspace/spec/spec.rb:110:in `block (3 levels) in <class:BasicSpec>'

13 runs, 7 assertions, 4 failures, 6 errors, 0 skips
Coverage report generated for RSpec to /home/ubuntu/workspace/coverage. 24 / 33 LOC (72.73%) covered.
rake aborted!
Command failed with status (1)
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Code ...
```
module Asynchronize
  def self.included(base)
    base.class_eval do
      
      def self.asynchronize(*methods)
        async_container = Asynchronize.get_container_for(self)
        # require 'pry'; binding.pry
        # puts async_container ## => Asynchronize::TestAsynchronized

        async_container.instance_eval do
          Asynchronize._define_methods_on_object(methods, self)
        end
      end
    end
  end

  private
  
  def self._define_methods_on_object(methods, obj)
    methods.each do |method|
      next if obj.methods.include?(method)
      obj.send(:define_method, method, _build_method)
    end
  end

  def self._build_method
    return Proc.new do |*args, &block|
      return Thread.new(args, block) do |thread_args, thread_block|
        Thread.current[:return_value] = super(*thread_args)
        thread_block.call(Thread.current[:return_value]) if thread_block
      end
    end
  end
  
  def self.get_container_for(obj)
    module_name = Asynchronize.get_container_name(obj.name) 
    if const_defined?(module_name) 
      async_container = const_get(module_name)
    else
      async_container = const_set(module_name, Module.new)
      prepend async_container
    end
    return async_container
  end
  
  def self.get_container_name(name)
    name = name.split('::').last + 'Asynchronized'
  end
end
```

**Comment by iCodeSometime** [comment]
It'll need to be changed to `obj.const_defined?`, `obj.cont_get`, `obj.const_set`, and `obj.prepend`.
Right now you're creating and prepending modules to Asynchronize.

Also, maybe an issue isn't the best place for this, since it's not an issue with the current code.
Maybe a gist would be better?

**Comment by Mirv** [comment]
I can't gist ...fire wall sorry - I could use the wiki?

I had tried the `obj` before, I'll go back & methodically hit them all up - ty! I just figured after 2 hours I should ask in case i'm off on a wild chase...

I just saw I needed to do prepend too - that's probably what it was ...

**Comment by iCodeSometime** [comment]
oh, ok.. you could always send me a link to the relevant lines in your fork?
Or really, even a pr could work since that's where it'll eventually go anyways

**Comment by iCodeSometime** [comment]
Actually you already have a PR for this, if you push those changes to the branch it's pulling from, then leave the error message as a comment that would work great :)
