### ISSUE TITLE
New version - just copy & pasted it into the repo

### ISSUE THREAD

**Issue by Mirv** [iCodeSometime/asynchronize#8]
My versions 
```
mirv:~/workspace (version2asyncAssigning) $ ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
mirv:~/workspace (version2asyncAssigning) $ rails -v
Rails 5.2.0
```

Then the initial rake ...
```
mirv:~/workspace (version2asyncAssigning) $ rake
Run options: --seed 23660

# Running:

EEEEEEEEEE.EEEEE

Finished in 0.005185s, 3085.9774 runs/s, 192.8736 assertions/s.

  1) Error:
Asynchronize::when we call asynchronized before defining the method#test_0001_should return a thread:
NoMethodError: private method `define_method' called for #<Module:0x00000001cd7b10>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:86:in `<class:Test>'
    /home/ubuntu/workspace/spec/spec.rb:85:in `block (3 levels) in <class:BasicSpec>'

  2) Error:
Asynchronize::when we call asynchronized before defining the method#test_0003_should provide the result as a block parameter:
NoMethodError: private method `define_method' called for #<Module:0x00000001cd5680>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:86:in `<class:Test>'
    /home/ubuntu/workspace/spec/spec.rb:85:in `block (3 levels) in <class:BasicSpec>'

  3) Error:
Asynchronize::when we call asynchronized before defining the method#test_0002_should provide the result in return_value:
NoMethodError: private method `define_method' called for #<Module:0x00000001cd4118>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:86:in `<class:Test>'
    /home/ubuntu/workspace/spec/spec.rb:85:in `block (3 levels) in <class:BasicSpec>'

  4) Error:
Asynchronize::when inheriting from another class#test_0002_should be able to call super when super has been asynchronized:
NoMethodError: private method `define_method' called for #<Module:0x000000024fb2d8>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:157:in `<class:Test>'
    /home/ubuntu/workspace/spec/spec.rb:156:in `block (3 levels) in <class:BasicSpec>'

  5) Error:
Asynchronize::when inheriting from another class#test_0001_should be able to call super when it's been asynchronized:
NoMethodError: private method `define_method' called for #<Module:0x000000024fa888>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:151:in `<class:ChildClassTest>'
    /home/ubuntu/workspace/spec/spec.rb:150:in `block (3 levels) in <class:BasicSpec>'

  6) Error:
Asynchronize::when there is an existing method_added#test_0001_should call that method_added before, and only once.:
NoMethodError: private method `define_method' called for #<Module:0x000000024f9988>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:123:in `<class:MethodAddedTest>'
    /home/ubuntu/workspace/spec/spec.rb:110:in `block (3 levels) in <class:BasicSpec>'

  7) Error:
Asynchronize::when we asynchronize a method#test_0001_should not be the same method:
NoMethodError: private method `define_method' called for #<Module:0x000000024f8a38>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:21:in `block (3 levels) in <class:BasicSpec>'

  8) Error:
Asynchronize::when we asynchronize a method#test_0003_should be the same method if we call a second time:
NoMethodError: private method `define_method' called for #<Module:0x000000024f81f0>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:29:in `block (3 levels) in <class:BasicSpec>'

  9) Error:
Asynchronize::when we asynchronize a method#test_0004_should not throw an error if the specified method does not exist:
NoMethodError: private method `define_method' called for #<Module:0x00000001cce650>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:37:in `block (3 levels) in <class:BasicSpec>'

 10) Error:
Asynchronize::when we asynchronize a method#test_0006_should not affect methods on other classes when called before:
NoMethodError: private method `define_method' called for #<Module:0x00000001ccd840>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:44:in `block (3 levels) in <class:BasicSpec>'

 11) Error:
Asynchronize::when we asynchronize a method#test_0005_should not create a method if the specified method does not exist:
NoMethodError: private method `define_method' called for #<Module:0x0000000250f288>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:40:in `block (3 levels) in <class:BasicSpec>'

 12) Error:
Asynchronize::when we asynchronize a method#test_0007_should not affect methods on other classes when called after:
NoMethodError: private method `define_method' called for #<Module:0x0000000250e978>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:57:in `block (3 levels) in <class:BasicSpec>'

 13) Error:
Asynchronize::when we call asynchronized after defining the method#test_0001_should return a thread:
NoMethodError: private method `define_method' called for #<Module:0x0000000250dbb8>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:65:in `block (3 levels) in <class:BasicSpec>'

 14) Error:
Asynchronize::when we call asynchronized after defining the method#test_0002_should provide the result in return_value:
NoMethodError: private method `define_method' called for #<Module:0x0000000250d348>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:65:in `block (3 levels) in <class:BasicSpec>'

 15) Error:
Asynchronize::when we call asynchronized after defining the method#test_0003_should provide the result as a block parameter:
NoMethodError: private method `define_method' called for #<Module:0x0000000250cad8>
Did you mean?  define_singleton_method
    /home/ubuntu/workspace/lib/asynchronize.rb:47:in `block in _define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `each'
    /home/ubuntu/workspace/lib/asynchronize.rb:45:in `_define_methods_on_object'
    /home/ubuntu/workspace/lib/asynchronize.rb:29:in `block in asynchronize'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `instance_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:28:in `asynchronize'
    /home/ubuntu/workspace/spec/spec.rb:65:in `block (3 levels) in <class:BasicSpec>'

16 runs, 1 assertions, 0 failures, 15 errors, 0 skips
Coverage report generated for RSpec to /home/ubuntu/workspace/coverage. 17 / 21 LOC (80.95%) covered.
rake aborted!
Command failed with status (1)
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)

```

**Comment by Mirv** [comment]
Better

**Comment by iCodeSometime** [comment]
Also, if you mean you copy-pasted the code; assuming you assigned my repo to a remote named upstream, you're probably looking for
`git pull upstream dev` :)

**Comment by Mirv** [comment]
Yea, doing that sometimes too
