### ISSUE TITLE
3 errors left from new version

### ISSUE THREAD

**Issue by Mirv** [iCodeSometime/asynchronize#9]
```
mirv:~/workspace (version2asyncAssigning) $ rake
Run options: --seed 43521

# Running:

......E.../home/ubuntu/workspace/lib/asynchronize.rb:48: warning: method redefined; discarding old test
/home/ubuntu/workspace/lib/asynchronize.rb:53: warning: previous definition of test was here
F.F...

Finished in 0.022986s, 696.0766 runs/s, 696.0766 assertions/s.

  1) Error:
Asynchronize::when there is an existing method_added#test_0001_should call that method_added before, and only once.:
NoMethodError: undefined method `+' for #<Thread:0x000000025e4258>
    /home/ubuntu/workspace/spec/spec.rb:118:in `block in method_added'
    /home/ubuntu/workspace/lib/asynchronize.rb:55:in `block (2 levels) in _build_method'

  2) Failure:
Asynchronize::when we asynchronize a method#test_0003_should be the same method if we call a second time [/home/ubuntu/workspace/spec/spec.rb:33]:
Asynchronized Inception has occurred.
No visible difference in the UnboundMethod#inspect output.
You should look at the implementation of #== on UnboundMethod or its members.
#<UnboundMethod: BasicSpec::Test(BasicSpec::Test::TestAsynchronized)#test>

  3) Failure:
Asynchronize::when we asynchronize a method#test_0005_should not create a method if the specified method does not exist [/home/ubuntu/workspace/spec/spec.rb:41]:
Expected: false
  Actual: true

16 runs, 16 assertions, 2 failures, 1 errors, 0 skips
Coverage report generated for RSpec to /home/ubuntu/workspace/coverage. 21 / 21 LOC (100.0%) covered.
rake aborted!
Command failed with status (1)
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
``

**Comment by Mirv** [comment]
Tweaked two things to make it go

**Comment by iCodeSometime** [comment]
@Mirv what did you tweak for this one?

**Comment by Mirv** [comment]
I had to blow out my old repository & then sync to the new dev branch you setup - was mostly a git scripting thing.
